language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

jdk:
  - oraclejdk8

before_install:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - ./gradlew build
  - fossa

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: 5RxwQ8GCxwIVZ/Op3lFiQFAqtBhNrp3sUDh8LgWR/icx1CZkxoooFb5osEjEkvxjH4KIT5Xnk85gVu5JzNqNxIUinFFgMmT+PtL0vp4mx5uYGgI+pJyxhLgVVsmhJ3R43nr/ziqDPIU21jA4v0XC5Wtn/XWaykOiM/9criUDMDGTMMCsJG/tT6n/vFBhduHW3sJKK74X2WzCU4b1zA5n9Od2z0xSzamkVWvq2SkwW/kLxeF/mowcOsjTCNMm2omAnUrs9iycOmQe0DOPOwlD1PvxJYpKkhn9KhhCETVqlPszzN59QgnuXQ1G0ubCfjVOXtr9tsPc0AML2/skCBKLsGUHr32TOkKADd57lASgdLz6s7zBMqqVEARu9uXGXOKRy78A2IeHNBZW4uLUKN0IBckMV0Uv8XXqLLl5hHD1EyMu3JuEoXuPGQXXMrL+puzfqJv34PtXdXFnRpWzR6La6mlJTaMG/Xs71o8cj143YwHabcgPENM/he9OizdGDTbwFiVGs1lfmecIg1eOr7OOJ3ywlUmuff5yYAk51g99YpVKCl53Uqf4WZrFelGeHoXTSdUoHOAM+WFFn5FdOTwiwhJyZ4mCrBokn9q/QI0Yqk4dXVUWOsB+KWM67OS7aoEtxJ8Ac5nYE9SIsmlze3FySbbUqjI9mTThGy1D8B5LG2Q=
    - secure: 5cBvEsqz8XA9Jd/T3trVkXPhTKxROpnFo4cCl3DFSd23t0rTOGPD0necU9WDycdk3PAryNvZA/+cOuGfe6vA8FtuOAa0X0txcmHw6M3JS9vOH4yoR31/JoZcBtJ6vHUnddoDzKGAZjDxZ81ni+RG3iJ11zfj7BIU2/8I8iqfCh9JGusvJR4aR5dz6QiGUnvmrdEN4sQxp+ryMUVxPgZLyQGFWwh1OE/rZvNkrpNlJ0OEo2ePP3yhN7l8fg37CqWK/HbAvKiN6NbJPd6q3bEtlzgTDS7FV0CtzPbkw3um8XtC/nqImCVg2LqKxk+eWXlOOAVMit9sAJ5QbxToKdd5Q9cO1uWLd+S6UsiaG5uKrZh6Qsscih8Xw2ewAC7IScE3Ru1hfTTNKht5AACMPs9wc2wnRk7XqYrd1qCZYEsWDOZv9Knzsm6neE3jeRk4xmBowISogd7cC6iyco9p8GedLCnnpGD6TZ2g2LDox04aaAM1TMD0C/Xu27Nii2O5ZP38MC/t9VJObeYP6p9Wgj9h0rq6TAfNvV8KN+PLB9QxiOv0EyvXn4v+stP0dJEfHmjm098DlidIyS3GaCd3/BJ2ARENHeWjyaNlqAUaxtofIPGE0wNdIofN7kGt9W6tPT5ed4B2aL652+O6daw9UsxyZyJx+tIOTT23qNf7OElF9mU=

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
